In [2]:
import torch
a =torch.Tensor([[0.46115, 0.05223],
        [0.35005, 0.31250],
        [0.60000, 0.31274],
        [0.31250, 0.53756],
        [0.65101, 0.55000],
        [0.24339, 0.79127],
        [0.71530, 0.79728]])

In [3]:
a

tensor([[0.4611, 0.0522],
        [0.3501, 0.3125],
        [0.6000, 0.3127],
        [0.3125, 0.5376],
        [0.6510, 0.5500],
        [0.2434, 0.7913],
        [0.7153, 0.7973]])

In [4]:
b = torch.stack((a,a))

In [5]:
b

tensor([[[0.4611, 0.0522],
         [0.3501, 0.3125],
         [0.6000, 0.3127],
         [0.3125, 0.5376],
         [0.6510, 0.5500],
         [0.2434, 0.7913],
         [0.7153, 0.7973]],

        [[0.4611, 0.0522],
         [0.3501, 0.3125],
         [0.6000, 0.3127],
         [0.3125, 0.5376],
         [0.6510, 0.5500],
         [0.2434, 0.7913],
         [0.7153, 0.7973]]])

In [6]:
slope = (b[1][-1][1] - b[1][-2][1])/(b[1][-1][0]-b[1][-2][0])
slope

tensor(0.0127)

In [7]:
#vectorized slope
c = (b[:,-2:,1][:,1] - b[:,-2:,1][:,0])/(b[:,-2:,0][:,1]- (b[:,-2:,0][:,0]))

In [8]:
slopes = torch.ones_like(c) #slope tensor 

In [9]:
slopes[c>0] = 1 #change slope accordingly
slopes[0] =1

In [10]:
# mid_pt = abs(output[1][0][-1] - output[1][0][-2]) * 
#\torch.Tensor([0.5,neg * 0.5]).to("cuda:0") + output[1][0][-2]

In [11]:
first = b[:,-2:,:][:,1] - b[:,-2:,:][:,0] 

In [12]:
sec = torch.ones_like(first)  * 0.5  * torch.stack((slopes,slopes),1)

In [13]:
b[:,-2]

tensor([[0.2434, 0.7913],
        [0.2434, 0.7913]])

In [14]:
third = b[:,-2]
third.shape

torch.Size([2, 2])

In [15]:
#compute mid_pts pose
mid_pts = first * sec + third

In [46]:
#compute height 
top = (mid_pts - b[:,0,:]) * 132 #
img_h = torch.norm(top,dim=1)
px_size = 6e-6 
hbb = px_size * img_h
cone_h = 0.3
f =1.2e-3
distance = f /(hbb*cone_h)

In [47]:
distance

tensor([6.8042, 6.8042])